server:
    port: 8805

spring:
    datasource:
        url: jdbc:mysql://192.168.16.34:41123/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: Password

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/

hawk:
    kubernetes:
        apiServer: https://192.168.16.34:6443
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpnTzQzTUFfdTlUQ0FEUTRWajJnVTg3Skw0c2RkVWVKeHJmUm9CTFYwaHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWo1bjI4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJjOTBhMWFkYS1lMmU4LTQyNjMtOGJkMi1iZWMxODkzNTRkNGMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.LtR_OWNuo2Y15aRzhV3cIjEzOoQwUhI_9etoh3p0fYa6pBuXJsYl_yfcLyqgaghwfS-5AKkl9F-KNlhQldtIMuEEPB2xnGz_66RQg9KvEYu1yNZgIrenxmNEgOwYxfqoRfm03MOVJXt-5Hb54uIiIuZX0Eylb3pUDgERbMDXUridYDpNh6I2xeoVsegw_T8eqHy0NdQGJJvtDPScB5hzsfzWXqd4STjylb7P77H2Px4oEtO0BvARkVGHa2qxS2LAnzV8gvEfDzEYigAsT8MnYSweg4lMB0CAxxIcqjywhlnb_YuxnL77hZvQxPgvLbJCT8VDxPp2ptLWKs_TAadTRg
